apiVersion: v1
kind: Namespace
metadata:
  name: mistake-5
---
apiVersion: v1
kind: Secret
metadata:
  name: tpp-mistake-5-secret
  namespace: mistake-5
data:
  password: UGFzc3dvcmQxMjMh
  username: dHBwYWRtaW4=
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: venafi-mistake-5-tpp-issuer
  namespace: mistake-5
spec:
  venafi:
    zone: "TLS/SSL\\Certificates\\Jetstack"
    tpp:
      url: https://<instance>/vedsdk # Change this to the URL of your TPP instance
      credentialsRef:
        name: tpp-mistake-5-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mistake-5
spec:
  secretName: mistake-5-secret
  dnsNames:
  - foo.example.com
  - bar.example.com
  issuerRef:
    name: venafi-mistake-5-tpp-issuer
    kind: Issuer
