apiVersion: v1
kind: Secret
metadata:
  name: tpp-mistake-3-secret
data:
  username: dHBwYWRtaW4=
  password: UGFzc3dvcmQxMjMh
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: venafi-mistake-3-tpp-issuer
spec:
  venafi:
    zone: "TLS/SSL\\Certificates\\Jetstack-restricted"
    tpp:
      url: https://<instance>/vedsdk # Change this to the URL of your TPP instance
      credentialsRef:
        name: tpp-mistake-3-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mistake-3
spec:
  secretName: mistake-3-secret
  commonName: cert-manager.lab.google.com
  issuerRef:
    name: venafi-mistake-3-tpp-issuer
    kind: Issuer
